language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t aababei/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true aababei/react-test npm test -- --coverage

after_success:
    - docker build -t aababei/multi-client ./client
    - docker build -t aababei/multi-nginx ./nginx
    - docker build -t aababei/multi-server ./server
    - docker build -t aababei/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push aababei/multi-client
    - docker push aababei/multi-nginx
    - docker push aababei/multi-server
    - docker push aababei/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-203875416728
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: 
        secure: "$AWS_ACCESS_KEY"
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"